# Site settings
title: TutorPages
email: rubensteinm@uchicago.edu
url: https://rubemat20.github.io/tutorPages/
description: "Your solution for creating a tutoring franchise in seconds"
keywords: "tutor, franchise, student, algorithm, popup"
skills: "Tutoring Setup - Algorithmic Pairing - Ease of Access"
meta_author: Mandel Max

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Stanford TreeHacks
  location: Location
  social: Around the Web
  credits: Credits
address:
  - line: University of Chicago
  
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/Rubemat20/tutorPages/

# Credits content
credits: 'TutorPages is a free to use, open source template, created using Freelancer, by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

# Collections
collections_dir: ""
collections:
  tutors:
    output: true
    permalink: "/tutors/:modal-id/"
    directory: "tutors"
  students:
    output: true
    permalink: "/students/:modal-id/"
    directory: "students"
